### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by sansarip** [manutter51/woolybear#2]
There seem to be references to some dependencies that aren't included in the repo which cause the Woolybear app to not compile.

For example:

- `woolybear.ad.catalog` requires `woolybear.packs.flex-panel`, `woolybear.packs.tab-panel`
- `woolybear.ad.catalog.containers` requires `woolybear.packs.flex-panel`

Is this intentional in that I'm meant to implement those packs myself?

**P.S.**
Sorry if this isn't really an issue and just a result of my inexperience with ClojureScript. I was intending to use your project as a learning platform in which I can explore atomic design, style frameworks, and ClojureScript + Re-frame - ending up with a neat little components catalog for future reference.

**Comment by sansarip** [comment]
The necessary cljs files needed to compile the Woolybear app were removed in commit `7359ecf7a6eef3dfd2e22537c928c66812a4929d`.

Solution is to checkout the prior commit: `33ecf1265fdf36569b229320f3554ecd0745abb2`.

**Comment by manutter51** [comment]
Thanks for reporting this, I've restored the deleted files, so you should be able to pull from master now.
